name: Node CI

on:
  push:
    branches:
     - master
  pull_request:
    branches:
     - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: build  

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and deploy Docker image
      run: |
        docker build -t calculator-node-js:staging .
        docker stop calculator-node-js || true
        docker rm calculator-node-js || true
        docker run -d -p 3000:3000 --name calculator-node-js calculator-node-js:staging
