name: Node CI

on:
  push:
    branches:
     - master
  pull_request:
    branches:
     - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
  deploy:
    runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and deploy
        run: |
          IMAGE_NAME="calculator-node-js"
          CONTAINER_NAME="calculator-node-js"
          PORT=3000

          echo "Starting deployment process..."
          echo "Building Docker image..."
          docker build -t ${IMAGE_NAME}:staging .
          echo "Stopping existing container (if any)..."
          docker stop ${CONTAINER_NAME} 2>/dev/null || true

          echo "Removing old container..."
          docker rm ${CONTAINER_NAME} 2>/dev/null || true

          echo "Running new container..."
          docker run -d -p ${PORT}:${PORT} --name ${CONTAINER_NAME} ${IMAGE_NAME}:staging

          echo "Deployment complete!"
        
